### ISSUE TITLE
Rewrite tests & run with gulp

### ISSUE THREAD

**Issue by brittanydionigi** [mozilla/node-firefox-start-simulator#1]

**Comment by lmorchard** [comment]
Started poking at this with a mock server script to stand in for an actual simulator. Works so far on darwin, going to try linux & win32 next.

**Comment by lmorchard** [comment]
So, I got a mock server working on win32, [but it's ugly](https://github.com/lmorchard/node-firefox-start-simulator/commit/88e34823096b684f5cdc62434eba45d087fb131a#diff-70e76b40cfe9bec1fb9891faf2768067R80).

**Comment by fwenzel** [comment]
Wow, you evil man

**Comment by lmorchard** [comment]
Finally got this working predictably on windows and submitted a PR: https://github.com/mozilla/node-firefox-start-simulator/pull/21
