### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox-start-simulator#10]
I am not familiar with any potential huge architectural differences between launching processes with Windows vs "POSIX" like Mac OS/Linux. Hopefully it will work the same, but I am not 100% sure we get things such as a PID that we can use to kill processes later in Windows.

**Comment by lmorchard** [comment]
Going to play with this more in the next week, but FWIW it seems like this already mostly works with the changes for WIndows in node-firefox-find-simulators

**Comment by lmorchard** [comment]
Got tests working, and windows support indeed seems to work out of the box!

https://github.com/mozilla/node-firefox-start-simulator/pull/21

**Comment by lmorchard** [comment]
Fixed with https://github.com/mozilla/node-firefox-start-simulator/commit/7ca46f60ec0e8541931fe28c6acffcef02ec114a
