### ISSUE TITLE
Renaming to node-firefox-start-simulator

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox-start-simulator#2]
I'd suggest changing the name of this module to start-simulator as it is more obvious what it does.

I had the same "issue" with fx-simulators which I renamed to find-simulators and makes more sense when you require it.

So you could do:

``` javascript
var startSimulator = require('node-firefox-start-simulator');
```

**Comment by tofumatt** [comment]
110% agree, start-simulator is a way better name.

-tofumatt

**Comment by brittanydionigi** [comment]
Renamed
