### ISSUE TITLE
The `options` parameter can be null but we're not taking it into account

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox-start-simulator#8]
So if you try to just `startSimulator().then(...)`, you get a

`
  var detached = options.detached ? true : false;
                        ^
TypeError: Cannot read property 'detached' of undefined
`

We need to add `options = options || {}` before accessing the `options`.

**Comment by tofumatt** [comment]
Fixed in e6327b3a148ccabf15b4022546df67055de079bc
